[build]
    base = "/"
    publish = "/"
    command = "python3 build.py"

    [[redirects]]
         from = "/api/patients/"
         to = "{{ API_PATIENTS_URL }}"
         status = 200
         force = true
         [redirects.headers] 
            Access-Control-Allow-Origin = "https://covidkashmir.org"