backend:
  name: git-gateway
  branch: master
collections:
  - name: data
    label: "Data"
    files:
      - label: "Pateient Data"
        name: "patient_data"
        file: "data/patient_data.json"
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Date, name: date, widget: string}
media_folder: "assets/images/uploads"
public_folder: "/images/uploads"
media_library:
  name: uploadcare
  config:
    publicKey: demopublickey
